### ISSUE TITLE
Wiimote not see in controleur VR

### ISSUE THREAD

**Issue by ghost** [ajayyy/Wiimote-FreePIE-VR-Controls#2]
Hello my wiimote looks working in freepie, but i don't have it on controlleur to steamVR, do u have some reason about it ?
![statut de steamvr](https://cloud.githubusercontent.com/assets/301074/25294327/f13ea0d2-26de-11e7-8ae2-d5576ea124c5.jpg)

please tell me where i can see wwhat's is wrong ?

**Comment by ajayyy** [comment]
Does FreePIE show data for the Wiimote? Are you using Vridge? And do you have the Razer Hydra Steam VR plugin? 

I haven't worked on this for a while because I was having some issues, so it might not be working 100%. But could you answer the top questions. It would help a lot, thanks

**Comment by ghost** [comment]
i m not using Vridge, i m using the Razer Hydra Steam Vr
![win64](https://cloud.githubusercontent.com/assets/301074/25295212/f784790e-26e2-11e7-91b7-8ec83513f256.jpg)


 Plugin, 

so in freepie, i can see some data change when i move front of my leapmotion, but i can 't see wiimote information
![freepie - programmable input emulator](https://cloud.githubusercontent.com/assets/301074/25295161/c17ee830-26e2-11e7-9294-093035c82d73.jpg)

i don't know why my steam dont see the controlleur
i put the dll files in : 
D:\Games\Steam\steamapps\common\SteamVR Driver for Razer Hydra
![steamvr driver for razer hydra](https://cloud.githubusercontent.com/assets/301074/25295193/e1dc348e-26e2-11e7-9364-f33c0db6f43e.jpg)

![win32](https://cloud.githubusercontent.com/assets/301074/25295233/0d8605d8-26e3-11e7-9feb-ab11b3a7033e.jpg)

**Comment by ghost** [comment]
do u have discord to contact u  ?
i create a channel just to talk to u ::
https://discord.gg/PYUvdbC

**Comment by ajayyy** [comment]
Hey the invite is expired. I think the probably for you is that you didn't replace sizsense fake with sizsense.dll. you have to delete the old and rename.

But the Wii mote issue is another thing. I don't think FreePIE is working correctly, as me and others can't get it to receive the numbers.

**Comment by ajayyy** [comment]
Can you maybe try the hydra test, to make sure at least the hydra emulation is working (because this emulates hydra controllers, which emulates steam controllers)

**Comment by ghost** [comment]
hello i update the link of discrod  
https://discord.gg/PYUvdbC

**Comment by ajayyy** [comment]
sstf submitted a fix for this. It should work now after hitting a button on the controller.
