### ISSUE TITLE
missing LeapCSharp.Net4.0

### ISSUE THREAD

**Issue by migero** [ajayyy/Wiimote-FreePIE-VR-Controls#3]
I'm getting this error when running the script i have installed leap drivers and downloaded sdk
![image](https://user-images.githubusercontent.com/12688112/32346397-a3e39812-bfe3-11e7-8d6a-52e46472befb.png)

I'm guessing it needs to know where to look for sdk ?

**Comment by ajayyy** [comment]
Sorry, didn't send all the plugin files, I'll upload the others right now.

**Comment by ajayyy** [comment]
Fixed
